// Mock product data (replace with actual data from API later)
export const products = [
  // Shoes
  {
    id: 'jordan-6-rings',
    name: 'Nike Air Jordan 6 Rings',
    price: 4249.99,
    rating: 4.9,
    reviews: 128,
    category: 'shoes',
    description: 'The Air Jordan 6 Rings combines elements from the 6 championship rings Michael Jordan earned during his illustrious career. This shoe features a premium leather upper with a clean, modern design that pays homage to the legacy of the greatest basketball player of all time.',
    features: [
      'Premium leather upper for durability and comfort',
      'Air cushioning for responsive feel',
      'Rubber outsole with herringbone pattern for traction',
      'Ankle strap for secure fit',
      'Jumpman logo on tongue and heel',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/Red', 'White/Black', 'Grey/Blue'],
    images: [
      '/JORDAN+6+RINGS-Photoroom.png',
      '/JORDAN+6+RINGS.avif',
      '/JORDAN+6+RINGS-2.avif',
    ],
    modelUrl: '/JORDAN+6+RINGS.glb',
  },
  {
    id: 'samba',
    name: 'adidas Samba OG Shoes',
    price: 2549.99,
    rating: 4.9,
    reviews: 95,
    category: 'shoes',
    description: 'The adidas Samba OG Shoes are a timeless classic that have been a favorite among soccer players and casual wearers alike for decades. These shoes feature a full grain leather upper, a gum rubber outsole, and the iconic 3-Stripes design.',
    features: [
      'Full grain leather upper for durability',
      'Gum rubber outsole for traction',
      'Classic 3-Stripes design',
      'Durable construction',
      'Versatile style for various activities',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/White', 'White/Black', 'Navy/White'],
    images: [
      '/Samba_OG_Shoes_White_JH5633_04_standard-Photoroom.png',
      '/Samba_OG_Shoes_White_JH5633_02_standard_hover-Photoroom.png',
      '/Samba_OG_Shoes_White_JH5633_03_standard-Photoroom.png',
    ],
    modelUrl: '/adidas Samba OG Shoes.glb',
  },
  {
    id: 'lamelo-shoes',
    name: 'PUMA x LAMELO BALL Golden Child',
    price: 3124.99,
    rating: 5.0,
    reviews: 78,
    category: 'shoes',
    description: 'The PUMA x LAMELO BALL Golden Child is a collaboration between PUMA and NBA star LaMelo Ball. These shoes feature a bold design with golden accents, premium materials, and innovative cushioning technology for optimal performance on and off the court.',
    features: [
      'Premium materials for comfort and durability',
      'Innovative cushioning technology',
      'Bold design with golden accents',
      'LaMelo Ball signature details',
      'Versatile style for basketball and casual wear',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/Gold', 'White/Gold', 'Blue/Gold'],
    images: [
      '/PUMA-x-LAMELO-BALL-MB.04-Golden-Child-Men\'s-Basketball-Shoes-Photoroom.png',
      '/PUMA-x-LAMELO-BALL-MB.04-Golden-Child-Men\'s-Basketball-Shoes-1.04-Golden-Child-Men\'s-Basketball-Shoes.png',
      '/PUMA-x-LAMELO-BALL-MB.04-Golden-Child-Men\'s-Basketball-Shoes3.png',
    ],
    modelUrl: '/PUMA x Lamelo Golden.glb',
  },
  {
    id: 'luka-3',
    name: 'Nike Air Jordan Luka 3',
    price: 3249.99,
    rating: 5.0,
    reviews: 112,
    category: 'shoes',
    description: 'The Nike Air Jordan Luka 3 is designed in collaboration with NBA star Luka Dončić. These shoes feature a lightweight construction, responsive cushioning, and a design inspired by Luka\'s playing style and heritage.',
    features: [
      'Lightweight construction for agility',
      'Responsive cushioning for impact protection',
      'Design inspired by Luka\'s playing style',
      'Heritage-inspired details',
      'Durable outsole for traction',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/Red', 'White/Blue', 'Grey/Orange'],
    images: [
      '/JORDAN+LUKA+3 (1)-Photoroom.png',
      '/JORDAN+LUKA+3 (2)-Photoroom.png',
      '/AURORA_FQ8185-500_PHSLH001-2000_3024x.jpg',
    ],
    modelUrl: '/Jordan Luka 3.glb',
  },
  {
    id: 'fenty-x-puma',
    name: 'FENTY x PUMA Avanti LS Stitched',
    price: 3644.99,
    rating: 4.8,
    reviews: 44,
    category: 'shoes',
    description: 'This is the Avanti LS like you’ve never seen it before. Appearing in two bold, beautiful colorways, the Avanti LS Stitched features crochet and stitching details and a classic soccer gum sole. Inspired by the legendary PUMA KING soccer cleat, the Avanti LS Stitched is here to play.',
    features: [
      'Regular fit for everyday comfort',
      'Premium tumbled leather upper for a refined look',
      'Hairy suede heel accent adds texture and contrast',
      'Tonal cotton laces with extra decorative set for added style',
      'Signature tongue flap with embroidered FENTY branding',
      'Crochet mesh underlay for breathability and detail',
      'Moulded sockliner for enhanced cushioning',
      'FENTY x PUMA co-branding for a unique collaboration touch',
    ]
    ,
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/Red', 'White/Black', 'Grey/Blue'],
    images: [
      '/FENTY-x-PUMA-Avanti-LS-Stitched-Men\'s-Sneakers-Photoroom.png',
      '/FENTY-x-PUMA-Avanti-LS-Stitched-Men\'s-Sneakers.avif',
      '/FENTY-x-PUMA-Avanti-LS-Stitched-Men\'s-Sneakers (1).avif',
    ],
  },
  {
    id: 'jordan-1-mid',
    name: 'Nike Air Jordan 1 Mid',
    price: 3124.99,
    rating: 4.6,
    reviews: 89,
    category: 'shoes',
    description: 'The Nike Air Jordan 1 Mid is a mid-top version of the iconic Air Jordan 1. These shoes feature a classic design with modern materials, offering style and comfort for everyday wear.',
    features: [
      'Classic Air Jordan 1 design',
      'Mid-top silhouette for ankle support',
      'Premium materials for durability',
      'Air cushioning for comfort',
      'Versatile style for various outfits',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
    colors: ['Black/Red', 'White/Black', 'Grey/Blue'],
    images: [
      '/WMNS+AIR+JORDAN+1+MID-Photoroom.png',
      '/WMNS+AIR+JORDAN+1+MID-Photoroom.png',
      '/WMNS+AIR+JORDAN+1+MID-Photoroom.png',
    ],
  },
  // Clothing
  {
    id: 'adidas-shorts',
    name: 'adidas Black Shorts Sports',
    price: 2549.99,
    rating: 4.9,
    reviews: 85,
    category: 'clothing',
    description: 'The adidas Black Shorts Sports are perfect for both training and casual wear. Made with lightweight, breathable fabric, these shorts offer comfort and freedom of movement.',
    features: [
      'Lightweight, breathable fabric',
      'Elastic waistband with drawstring',
      'Side pockets for storage',
      '3-Stripes design',
      'Quick-drying material',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Grey'],
    images: [
      '/AEROREADY_Designed_to_Move_Woven_Sport_Shorts_Black_GT8161_01_laydown-Photoroom.png',
      '/AEROREADY_Designed_to_Move_Woven_Sport_Shorts_Black_GT8161_01_laydown-Photoroom.png',
      '/AEROREADY_Designed_to_Move_Woven_Sport_Shorts_Black_GT8161_01_laydown-Photoroom.png',
    ],
  },
  {
    id: 'adidas-pants',
    name: 'Tiro 24 Training Pants',
    price: 3124.99,
    rating: 5.0,
    reviews: 92,
    category: 'clothing',
    description: 'The Tiro 24 Training Pants are a modern take on the classic track pants. With a tapered fit and premium materials, these pants offer style and comfort for everyday wear.',
    features: [
      'Premium cotton blend fabric',
      'Tapered fit for modern style',
      'Elastic waistband with drawstring',
      'Side pockets for storage',
      '3-Stripes design',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Grey'],
    images: [
      '/3-Stripes_Tricot_Regular_Tapered_Track_Pants_Black_JI8809_01_laydown-Photoroom.png',
      '/3-Stripes_Tricot_Regular_Tapered_Track_Pants_Black_JI8809_02_laydown-Photoroom.png',
      '/3-Stripes_Tricot_Regular_Tapered_Track_Pants_Black_JI8809_03_laydown-Photoroom.png',
    ],
  },
  {
    id: 'adidas-hoodie',
    name: 'adidas NY Bulls Red Hoodie',
    price: 1999.99,
    rating: 4.8,
    reviews: 76,
    category: 'clothing',
    description: 'The adidas NY Bulls Red Hoodie is a stylish and comfortable hoodie perfect for showing your team spirit. Made with soft, warm fabric, this hoodie is ideal for casual wear.',
    features: [
      'Soft, warm fabric',
      'Kangaroo pocket',
      'Adjustable hood',
      'Ribbed cuffs and hem',
      'Team logo design',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red', 'Black', 'White'],
    images: [
      '/New_York_Red_Bulls_UBP_Travel_Hoodie_Red_JE5524_01_laydown-Photoroom.png',
      '/New_York_Red_Bulls_UBP_Travel_Hoodie_Red_JE5524_02_laydown-Photoroom.png',
      '/New_York_Red_Bulls_UBP_Travel_Hoodie_Red_JE5524_03_laydown-Photoroom.png',
    ],
  },
  {
    id: 'puma-tee',
    name: 'PUMA Blue Tee',
    price: 4249.99,
    rating: 4.9,
    reviews: 88,
    category: 'clothing',
    description: 'The PUMA Blue Tee is a comfortable and stylish t-shirt perfect for everyday wear. Made with soft, breathable fabric, this tee offers comfort and style.',
    features: [
      'Soft, breathable fabric',
      'Regular fit',
      'PUMA logo design',
      'Machine washable',
      'Comfortable collar',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Black', 'White'],
    images: [
      '/ESS-No.-1-Logo-Men\'s-Tee-Photoroom.png',
      '/PUMA Blue Tee-1.jpg',
      '/PUMA Blue Tee-2.jpg',
    ],
  },
  {
    id: 'fenty-tee',
    name: 'F1 Men\'s Japan',
    price: 3124.99,
    rating: 4.6,
    reviews: 67,
    category: 'clothing',
    description: 'The F1 Men\'s Japan tee is a stylish t-shirt featuring F1 racing design. Made with comfortable fabric, this tee is perfect for showing your love for Formula 1 racing.',
    features: [
      'Comfortable cotton fabric',
      'Regular fit',
      'F1 racing design',
      'Machine washable',
      'Comfortable collar',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Red'],
    images: [
      '/F1®-Japan-Men\'s-Tee-Photoroom.png',
      '/F1®-Japan-Men\'s-Tee-02-Photoroom.png',
      '/F1®-Japan-Men\'s-Tee-03-Photoroom.png',
    ],
  },
  // Accessories
  {
    id: 'legacy-cap',
    name: 'Nike Dri-FIT Legacy91 Cap',
    price: 624.99,
    rating: 4.8,
    reviews: 156,
    category: 'accessories',
    description: 'The Nike Dri-FIT Legacy91 Cap is a classic baseball cap with modern performance features. Made with Dri-FIT technology, this cap keeps you cool and dry during activities.',
    features: [
      'Dri-FIT technology for moisture management',
      'Adjustable strap',
      'Curved brim',
      'Nike logo design',
      'Machine washable',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'White'],
    images: [
      '/U+NK+DF+L91+SPORT+CAP.avif',
      '/U+NK+DF+L91+SPORT+CAP (1).avif',
      '/U+NK+DF+L91+SPORT+CAP (2).avif',
    ],
  },
  {
    id: 'classic-backpack',
    name: 'adidas Classic Backpack',
    price: 1149.99,
    rating: 4.7,
    reviews: 124,
    category: 'accessories',
    description: 'The adidas Classic Backpack is a versatile and durable backpack perfect for everyday use. With multiple compartments and comfortable straps, this backpack offers style and functionality.',
    features: [
      'Multiple compartments',
      'Laptop sleeve',
      'Comfortable shoulder straps',
      '3-Stripes design',
      'Water-resistant material',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Grey'],
    images: [
      '/Adicolor_Backpack_Black_IJ0761_01_standard.avif',
      '/Adicolor_Backpack_Black_IJ0761_02_standard.avif',
      '/Adicolor_Backpack_Black_IJ0761_04_standard.avif',
    ],
  },
  {
    id: 'evercat-duffel',
    name: 'PUMA Evercat Transformation Duffel',
    price: 999.99,
    rating: 4.5,
    reviews: 98,
    category: 'accessories',
    description: 'The PUMA Evercat Transformation Duffel is a versatile bag that can be used as a duffel or backpack. With multiple compartments and comfortable straps, this bag offers style and functionality.',
    features: [
      'Convertible design',
      'Multiple compartments',
      'Comfortable straps',
      'PUMA logo design',
      'Water-resistant material',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Red'],
    images: [
      '/81TVD-lLmPL._AC_SX569_.png',
      '/81BuhSMF2QL._AC_SX569_.jpg',
      '/718dhB9xP5L._AC_SX569_.jpg',
    ],
  },
  {
    id: 'brasilia-gymsack',
    name: 'Nike Brasilia Training Gymsack',
    price: 499.99,
    rating: 4.9,
    reviews: 112,
    description: 'The Nike Brasilia Training Gymsack is a durable and spacious gym bag perfect for carrying your workout essentials. With multiple compartments and comfortable straps, this bag offers style and functionality.',
    features: [
      'Multiple compartments',
      'Comfortable shoulder strap',
      'Nike logo design',
      'Water-resistant material',
      'Durable construction',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Navy', 'Grey'],
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
      '/placeholder.svg',
    ],
  },
  {
    id: 'originals-socks',
    name: 'adidas Originals Socks 3-Pack',
    price: 424.99,
    rating: 4.6,
    reviews: 89,
    description: 'The adidas Originals Socks 3-Pack includes three pairs of comfortable and stylish socks. Made with soft, breathable fabric, these socks offer comfort and style.',
    features: [
      'Soft, breathable fabric',
      'Comfortable fit',
      '3-Stripes design',
      'Machine washable',
      'Durable construction',
    ],
    sizes: ['One Size'],
    colors: ['Black/White', 'White/Black', 'Grey/Black'],
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
      '/placeholder.svg',
    ],
  },
  {
    id: 'elite-socks',
    name: 'Nike Elite Basketball Socks',
    price: 474.99,
    rating: 4.7,
    reviews: 134,
    category: 'accessories',
    description: 'The Nike Elite Basketball Socks are designed for optimal performance on the court. With cushioned support and moisture-wicking technology, these socks keep your feet comfortable during intense games.',
    features: [
      'Moisture-wicking technology',
      'Cushioned support',
      'Arch compression',
      'Reinforced heel and toe',
      'Dynamic fit',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black/White', 'White/Black', 'Grey/Black'],
    images: [
      '/U+NK+ELITE+CREW+132.avif',
      '/U+NK+ELITE+CREW+132 (1).avif',
      '/U+NK+ELITE+CREW+132 (2).avif',
    ],
  },
  {
    id: 'pioneer-wallet',
    name: 'PUMA Pioneer Wallet',
    price: 649.99,
    rating: 4.5,
    reviews: 92,
    category: 'accessories',
    description: 'The PUMA Pioneer Wallet is a sleek and functional accessory for everyday use. With multiple card slots and a billfold compartment, this wallet combines style with practicality.',
    features: [
      'Multiple card slots',
      'Billfold compartment',
      'PUMA logo design',
      'Durable material',
      'Slim profile',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Brown', 'Navy'],
    images: [
      '/Pioneer-Wallet.avif',
      '/Pioneer-Wallet (1).avif',
      '/Pioneer-Wallet (2).avif',
    ],
  },
  {
    id: 'training-gloves',
    name: 'adidas Training Gloves',
    price: 749.99,
    rating: 4.6,
    reviews: 78,
    category: 'accessories',
    description: 'The adidas Training Gloves provide essential protection and grip for your workout sessions. With breathable material and reinforced padding, these gloves enhance your training experience.',
    features: [
      'Breathable material',
      'Reinforced padding',
      'Secure wrist closure',
      'Non-slip grip',
      'Machine washable',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black/White', 'Grey/Black', 'Blue/White'],
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
      '/placeholder.svg',
    ],
  },
  {
    id: 'resistance-band',
    name: 'Nike Resistance Band Set',
    price: 874.99,
    rating: 4.8,
    reviews: 156,
    category: 'accessories',
    description: 'The Nike Resistance Band Set includes multiple resistance levels for versatile workout options. Perfect for strength training, rehabilitation, or adding intensity to your exercises.',
    features: [
      'Multiple resistance levels',
      'Durable latex material',
      'Non-slip grip',
      'Carrying bag included',
      'Exercise guide included',
    ],
    sizes: ['One Size'],
    colors: ['Light', 'Medium', 'Heavy'],
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
      '/placeholder.svg',
    ],
  },
  {
    id: 'performance-headband',
    name: 'PUMA Performance Headband',
    price: 324.99,
    rating: 4.4,
    reviews: 112,
    category: 'accessories',
    description: 'The PUMA Performance Headband keeps sweat away from your eyes during intense workouts. Made with moisture-wicking material and featuring a comfortable fit, this headband is essential for any active lifestyle.',
    features: [
      'Moisture-wicking material',
      'Comfortable fit',
      'PUMA logo design',
      'Machine washable',
      'Non-slip grip',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'White', 'Grey'],
    images: [
      '/placeholder.svg',
      '/placeholder.svg',
      '/placeholder.svg',
    ],
  },
];

// Function to get product by ID
export function getProductById(id: string) {
  return products.find(product => product.id === id);
}

// Function to get product by name
export function getProductByName(name: string) {
  return products.find(product => product.name === name);
}

// Function to get similar products (excluding the current product)
export function getSimilarProducts(currentProductName: string, count: number = 6) {
  const currentProduct = getProductByName(currentProductName);
  if (!currentProduct) return [];
  
  // Filter out the current product and get random products
  const otherProducts = products.filter(product => product.name !== currentProductName);
  
  // Shuffle the array to get random products
  const shuffled = [...otherProducts].sort(() => 0.5 - Math.random());
  
  // Return the first 'count' products
  return shuffled.slice(0, count);
} 